#!/bin/sh

update-resolve

set -e
set -x

if [ "yes" == "${RUN_IN_DOCKER}" ]; then
	CONFIG=/data/config/nginx.conf
	echo "proxy_cache_path /data/cache levels=1:2 keys_zone=my_cache:10m max_size=10g
                           inactive=60m use_temp_path=off;" > /data/config/conf.d/cache.conf
else
	CONFIG="$(pwd)/config/nginx.conf"
	echo "proxy_cache_path $(pwd)/cache levels=1:2 keys_zone=my_cache:10m max_size=10g
                           inactive=60m use_temp_path=off;" > $(pwd)/config/conf.d/cache.conf
fi

RESOLVERS="$(
)"

RESOLVE_FILE_PATH=$(pwd)/config/resolv.conf
echo resolver > "${RESOLVE_FILE_PATH}"

set +e
grep nameserver /etc/resolv.conf |
	grep -v 127.0.0.1 |
	grep -v 172.17.0 |
	grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' >> "${RESOLVE_FILE_PATH}"
set -e

echo ';'  >> "${RESOLVE_FILE_PATH}"

echo "try start nginx server."

nginx -c "$CONFIG" -g "daemon off;"
