#!/bin/sh

set -e
set -x

if [ "yes" == "${RUN_IN_DOCKER}" ]; then
	ROOT=/data
else
	ROOT=$(pwd)
fi

CONFIG="${ROOT}/config"

echo "proxy_cache_path ${ROOT}/cache levels=1:2 keys_zone=my_cache:10m max_size=10g
					   inactive=60m use_temp_path=off;" > ${CONFIG}/conf.d/cache.conf

RESOLVE_FILE_PATH=${CONFIG}/resolv.conf
echo resolver > "${RESOLVE_FILE_PATH}"

	grep nameserver /etc/resolv.conf  |
	grep -v 127.0.0.1 |
	grep -v 172.17.0 |
	grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' >> "${RESOLVE_FILE_PATH}"

echo ';'  >> "${RESOLVE_FILE_PATH}"

echo "try start nginx server."

cat /etc/resolv.conf
cat "${RESOLVE_FILE_PATH}"

nginx -c "${CONFIG}/nginx.conf" -g "daemon off;"
